add lecture04.md
hikaru0313/raisetech pull request #4
Opened 2023-07-10 12:03 UTC by hikaru0313

第４回課題を提出します。

2023-07-10 17:09 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご対応くださいませ！

2023-07-10 17:09 UTC, MasatoshiMizumoto commented on lecture04.md
画像は「アップロード」で登録するのではなく、gitを通じてpushしていただき、それを参照する形でMarkdownを書いていただきたいです！

2023-07-11 03:19 UTC, hikaru0313 commented on lecture04.md
変更いたしました、ご確認をお願いいたします。

2023-07-11 06:21 UTC, MasatoshiMizumoto approved these changes
LGTM!

2023-07-11 10:10 UTC, merged