Lecture05
hikaru0313/raisetech pull request #5
Opened 2023-09-02 13:56 UTC by hikaru0313

第５回課題提出します

2023-09-02 14:08 UTC, MasatoshiMizumoto requested changes
コメント入れましたのでご確認と対応よろしくお願いします！！

2023-09-02 14:08 UTC, MasatoshiMizumoto commented on lecture05.md
途中まで画像のサムネが出ていないので、見る人は理由が気になると思います！
課題の文章を満たした様式ではあるのですが、開発した機能の報告とレビューがプルリクエストなので、
補足の文章を入れてほしいです！

2023-09-02 14:08 UTC, MasatoshiMizumoto commented on lecture05/lecture05構成図.jpg
このくらいのAWSサービス種類とレビュアーがエンジニアという前提であればこれでOKですが、
対納品先などに書くとなるとサービス名は無いと視認性が悪いかなと思いました！

2023-09-02 14:24 UTC, hikaru0313 commented on lecture05.md
すみません、画像ですが「view file」から直接"lecture05.md"にアクセスすると表示されるのですが、PRの画面では表示されていないみたいです。
何か原因はありますでしょうか。

2023-09-02 14:48 UTC, hikaru0313 commented on lecture05.md
連投失礼します。
第４回のmarkdownファイルをコピペして、先にpushしてから内容を第５回の内容に合わせて書き換えてしまい、その履歴が残っているせいで表示が変になってしまっていると思ったのですがどうでしょうか…

2023-09-02 15:03 UTC, hikaru0313 commented on lecture05/lecture05構成図.jpg
こちら追記しました。ご確認お願い致します。

2023-09-02 15:59 UTC, MasatoshiMizumoto commented on lecture05.md
あ、Markdownがどうという話ではなく、Railsアプリケーションのスクショに対して途中まで画像のサムネ表示に対応していない（アプリケーションとしてバグがあるように見える）ことについて理由を書いた方が良いのではという話です！

2023-09-02 16:00 UTC, MasatoshiMizumoto commented on lecture05/lecture05構成図.jpg
はい、こちらで構成図はOKです！

2023-09-03 04:56 UTC, hikaru0313 commented on lecture05.md
勘違いしてすみません…
正直に言いますと、初めのデプロイの時から「どうしたら画像のサムネイルが表示されるのか」というのは気になっていたのですが、S3を導入したら何故か表示されるようになったので、理由がわからないです…

2023-09-03 04:57 UTC, hikaru0313 commented on lecture05/lecture05構成図.jpg
ありがとうございます

2023-09-04 01:15 UTC, MasatoshiMizumoto commented on lecture05.md
なるほど、ではその旨書いておいて良いと思います！
この報告は学習記録の要素もあるので、分かってないことを書いても問題ないです！

2023-09-04 01:16 UTC, MasatoshiMizumoto approved these changes
挙動がわかっていない部分だけ追記してもらってマージでOKです！
お疲れさまでした！

2023-09-04 01:30 UTC, hikaru0313 commented on lecture05.md
承知しました、ありがとうございます。

2023-09-04 01:30 UTC, merged